(;GM[1]FF[4]RU[Chinese]SZ[19]KM[0.5]PB[Leela 0.10.0]PW[Human]HA[6]RE[B+31.5]
AB[dp][dj][dd][pp][pj][pd]
;W[cf];B[fc];W[bd];B[cc];W[ch];B[ci];W[dh];B[cm];W[nq];B[pn]
;W[jp];B[hp];W[nc];B[pf];W[pb];B[qc];W[kc];B[ic];W[cq];B[dq]
;W[cp];B[co];W[bo];B[bn];W[do];B[cn];W[dr];B[er];W[br];B[ds]
;W[cs];B[cr];W[qq];B[bs];W[pq];B[qp];W[qh];B[qg];W[ph];B[qb]
;W[pl];B[ql];W[qk];B[pk];W[qm];B[rl];W[pm];B[rm];W[qn];B[rn]
;W[qj];B[qo];W[nl];B[on];W[nm];B[nj];W[nh];B[lj];W[lh];B[jj]
;W[km];B[jh];W[rp];B[ro];W[rq];B[op];W[mo];B[np];W[mq];B[rk]
;W[rj];B[kg];W[mf];B[le];W[lf];B[kf];W[ke];B[kd];W[je];B[ld]
;W[jd];B[lc];W[jc];B[nd];W[ki];B[kj];W[ji];B[ii];W[ih];B[ig]
;W[hh];B[kb];W[jb];B[hg];W[gh];B[hj];W[gd];B[ff];W[gg];B[he]
;W[gf];B[ie];W[ge];B[hc];W[lb];B[mb];W[ka];B[mc];W[gc];B[gb]
;W[hb];B[ib];W[fb];B[ha];W[ec];B[eb];W[fa];B[fd];W[ed];B[fe]
;W[db];B[ee];W[ea];B[cb];W[ga];B[hb];W[hd];B[id];W[if];B[hf]
;W[jf];B[jg];W[lg];B[ja];W[ia];B[ce];W[be];B[ja];W[ik];B[ij]
;W[ia];B[mp];W[lp];B[ja];W[no];B[oo];W[ia];B[lo];W[ln];B[ja]
;W[mk];B[kb];W[mj])
